/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/Header.vue')['default']
    ScrollContainer: typeof import('./src/components/ScrollContainer.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
  }
}
